@baseUrl = http://localhost:3001
### New
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "Zaq1@wsxcde3"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "Zaq1@wsxcde3"
}

### Get current user
GET {{baseUrl}}/users